### PR TITLE
Migrated to new React 16.8 Hooks

### PR DESCRIPTION
**Pull request by anselm94**
- Replaced React Class Components with React Hooks
- Uses `useState`, `useEffect` and `useRef` hooks to exactly represent the existing Class Components based code structure

### CODE REVIEW

**Comment by anselm94** [comment]
@fifoosid will update the PR ASAP

**Comment by anselm94** [comment]
@fifoosid 

- [x] React version updated to 16.8 and above
- [x] Fixed performance issues with `useCallback` hook
- [x] Fixed single quotes

**Comment by fifoosid** [comment]
Hi @anselm94 

Thanks for the contribution. 😄 

Best regards,
Filip

**Comment by anselm94** [comment]
🎉

**Pull request merged**
